## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

git:
  depth: 99999999

# matrix:
#  allow_failures:
#  - julia: nightly

before_script:
 - if [ $TRAVIS_OS_NAME = linux ]; then
     sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
     sudo apt-get update -qq;
     sudo apt-get install -qq gcc-5 g++-5;
     sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5;

     wget http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo/pool/xenial/main/libr/librealsense2/librealsense2_2.10.4-0~realsense0.67_amd64.deb;
     sudo dpkg -i librealsense2_2.10.4-0~realsense0.67_amd64.deb;
     wget http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo/pool/xenial/main/libr/librealsense2/librealsense2-dev_2.10.4-0~realsense0.67_amd64.deb;
     sudo dpkg -i librealsense2-dev_2.10.4-0~realsense0.67_amd64.deb;
   fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("RealSense"); Pkg.test("RealSense"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("RealSense")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder("gen/api"));'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("RealSense")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder("gen/api"));'
